# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: vocab.proto
# Protobuf Python Version: 6.33.4
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    4,
    '',
    'vocab.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0bvocab.proto\x12\x0b\x66lashrecall\"\xcd\x01\n\x04Word\x12\n\n\x02id\x18\x01 \x01(\x05\x12\r\n\x05lemma\x18\x02 \x01(\t\x12\x0f\n\x07wortart\x18\x03 \x01(\t\x12\r\n\x05genus\x18\x04 \x01(\t\x12\x0f\n\x07\x61rtikel\x18\x05 \x01(\t\x12\r\n\x05level\x18\x06 \x01(\t\x12\x11\n\tfrequency\x18\x07 \x01(\t\x12\x0f\n\x07\x65nglish\x18\x08 \x01(\t\x12\x16\n\x0egerman_example\x18\t \x01(\t\x12\x17\n\x0f\x65nglish_example\x18\n \x01(\t\x12\x15\n\rnur_im_plural\x18\x0b \x01(\t\"C\n\x0eVocabularyData\x12\x0f\n\x07version\x18\x01 \x01(\x05\x12 \n\x05words\x18\x02 \x03(\x0b\x32\x11.flashrecall.Word\"\xb8\x01\n\x0cWordProgress\x12\x0f\n\x07word_id\x18\x01 \x01(\x05\x12\x11\n\tstability\x18\x02 \x01(\x01\x12\x12\n\ndifficulty\x18\x03 \x01(\x01\x12\x10\n\x08\x64ue_date\x18\x04 \x01(\x03\x12\x14\n\x0c\x65lapsed_days\x18\x05 \x01(\x01\x12\x16\n\x0escheduled_days\x18\x06 \x01(\x01\x12\x0c\n\x04reps\x18\x07 \x01(\x05\x12\r\n\x05state\x18\x08 \x01(\x05\x12\x13\n\x0blast_review\x18\t \x01(\x03\";\n\x0cProgressData\x12+\n\x08progress\x18\x01 \x03(\x0b\x32\x19.flashrecall.WordProgressb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'vocab_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_WORD']._serialized_start=29
  _globals['_WORD']._serialized_end=234
  _globals['_VOCABULARYDATA']._serialized_start=236
  _globals['_VOCABULARYDATA']._serialized_end=303
  _globals['_WORDPROGRESS']._serialized_start=306
  _globals['_WORDPROGRESS']._serialized_end=490
  _globals['_PROGRESSDATA']._serialized_start=492
  _globals['_PROGRESSDATA']._serialized_end=551
# @@protoc_insertion_point(module_scope)
